package org.battelle.clodhopper;

import java.util.List;
import java.util.concurrent.ExecutionException;

import org.battelle.clodhopper.task.AbstractTask;

public abstract class AbstractClusterer extends AbstractTask<List<Cluster>> 
	implements Clusterer {

	protected AbstractClusterer() {}
	
	@Override
	/**
	 * Returns the clusters generated by this clusterer if clustering has
	 * run to completion successfully.  Otherwise, this method returns null.
	 * This method should only be called after ascertaining that the clusterer has finished 
	 * with an outcome of TaskOutcome.SUCCESS.  The purpose of this method is to
	 * provide an alternative to <code>get()</code> which does not have to be enclosed in
	 * a try-catch clause.
	 */
	public List<Cluster> getClusters() {
		List<Cluster> clusters = null;
		try {	
			clusters = get();
		} catch (InterruptedException e) {
		} catch (ExecutionException e) {
		}
		return clusters;
	}
}
