package org.battelle.clodhopper;

/**
 * The exception type that is generated by errors during clustering operations.
 * 
 * @author R. Scarberry
 * @since 1.0
 *
 */
public class ClusteringException extends Exception {

	private static final long serialVersionUID = -4785484683342476830L;

	public ClusteringException(String message) {
		super(message);
	}
	
}
